repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: nginx-bitnami
  url: oci://registry-1.docker.io/bitnamicharts/nginx

releases:
- name: prom-norbac-ubuntu
  namespace: prometheus
  chart: prometheus-community/prometheus
  set:
  - name: rbac.create
    value: false
- name: nginx
  namespace: nginx
  chart: nginx-bitnami/nginx
# - name: postgresql
#   namespace: default
#   chart: bitnami/postgresql
#   values:
#     - auth:
#         username: my-user
#         password: my-password
