repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: prom-norbac-ubuntu
  createNamespace: true 
  namespace: prometheus
  chart: prometheus-community/prometheus
  set:
  - name: rbac.create
    value: false
- name: nginx
  namespace: nginx
  createNamespace: true 
  chart: bitnami/nginx
  set:
  - name: controller.replicaCount
    value: 2
# - name: postgresql
#   namespace: default
#   chart: bitnami/postgresql
#   values:
#     - auth:
#         username: my-user
#         password: my-password
