apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: minikube-charts
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: helmfile-namespace
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: latest  # For Helm, this refers to the chart version.
    chart: nginx
    helm:
      valuesObject:
        replicaCount: 3
      version: v3
  syncPolicy:
    automated:
      prune: true    # Automatically remove resources not declared in the source repository
      selfHeal: true # Automatically reapply manifests if they drift from the desired state
    syncOptions:
      - CreateNamespace=true
